apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: s9pr59pww-python
  janus-idp.io/tekton: s9pr59pww-python
  backstage.io/kubernetes-id: s9pr59pww-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: s9pr59pww-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
